[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { path = "../sdk" }
directories = "6.0"
eyre = "0.6"
macroquad = "0.4"
tokio = { version = "1.39", features = ["full"] }
